name: Build Artifacts

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci
    
    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Windows
        path: dist/*.exe

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:linux

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Linux
        path: dist/*.AppImage

  build-macos:
    name: MacOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:mac

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: MacOS
        path: dist/*.dmg
