name: Build

on:
  push:
    branches: [ main ]

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

    - name: Install dependencies
      run: npm ci
    
    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:win
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:linux
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-macos:
    name: MacOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2.3.4

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:mac
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
