name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci
    
    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:win

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:linux

  build-macos:
    name: MacOS
    runs-on: macOS-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Install dependencies
      run: npm ci

    - name: ESLint
      run: npm run lint

    - name: Build
      run: npm run dist:mac
